[package]
name = "rust-trie"
version = "0.1.0"
authors = ["Dillon Sellars <dillon.sellars@earlywarning.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
